### ISSUE TITLE
SVM's Solution

### ISSUE THREAD

**Issue by amirjamez** [ppaquay/Learning-from-Data-Solutions#2]
Hey @ppaquay. Do you happen to have the solutions for the SVMs (chapter 8)? Say 8.2 and 8.8 maybe? 
Thanks

**Comment by ppaquay** [comment]
Hi Amir,

Not yet, but I'm planning to do that shortly.

Best regards.

**Comment by ppaquay** [comment]
Solution to problem 8.2 is online. Solution to problem 8.8 will follow.

Regards.
