### ISSUE TITLE
Problem 1.9 (b)

### ISSUE THREAD

**Issue by silpian** [ppaquay/Learning-from-Data-Solutions#3]
<img width="637" alt="problem1 9b" src="https://user-images.githubusercontent.com/26121765/60284038-30bfb380-98d0-11e9-9a19-f365435bdef3.png">

I think the last step should be:

(e^(-s*alpha)*U(s))^N

instead of

(e^(-s*N*alpha)*U(s))^N.

Also, I don't know why, in the 2nd to 3rd step, 

E(e^(s*N*u)) = product of E(e^(s*u_n)) for all n. Thanks!

**Comment by ppaquay** [comment]
HI,
I guess you're right, I put a supplementary N that shouldn't be there.
Concerning your question, you can write:
E(e^(sNU)) = E(e^(sum s*u_n)) = prod E(e^(s*u_n)) since the u_n (and consequently e^(s*u_n) are independant).
Hope this helps !
