### ISSUE TITLE
Problem 1.12 b)

### ISSUE THREAD

**Issue by silpian** [ppaquay/Learning-from-Data-Solutions#4]
<img width="762" alt="problem" src="https://user-images.githubusercontent.com/26121765/60400663-9ca65400-9b3c-11e9-9044-30b135d6472f.png">

I think the derivative of E should be piecewise.
```
dE/dh = sum( d(|h-y_n|)/dh )
```
where
```
d|h-y_n|/dh = 1        if h-y_n > 0
             -1        if h-y_n < 0
             undefined if h-y_n = 0
```
Then it follows that the h that minimizes E is one where half of the y points are below and half are above the h.

Also, thank you for answering my last question!

**Comment by ppaquay** [comment]
Hi silpian,
Actually, I forgot to write the denominator, it should read as sum((h - y_n)/|h-y_n|). My bad !
Anyway, your solution is also correct.
Thanks !
